name: Format with black and isort

on:
  push:
    branches: [main]
    paths:
      - "pathsearch.py"
      - "test/**"

  pull_request:
    branches: [main]
    paths:
      - "pathsearch.py"
      - "test/**"

jobs:
  format:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install poetry
        run: python -m pip install poetry

      - name: Cache Poetry deps
        uses: actions/setup-python@v3
        with:
          cache: poetry

      - name: Install deps if they weren't restored from cache
        run: poetry install

      - name: Run black
        run: |
          poetry run `
            black `
              ${{ github.workspace }} `
              ${{ github.workspace }}\test `
              --check

      - name: Run isort
        run: |
          poetry run `
            isort `
              ${{ github.workspace }} `
              ${{ github.workspace }}\test `
              --check
